export const metadata = {
    title: "Contact",
    description: "Generated by create next app",
  };
  
  export default function RootLayout({ children }) {
    return (
      <html lang="en">
        <body>This Contact Page{children}</body>
      </html>
    );
  }
  